language: python
sudo: false
os:
  - linux

python:
  - "2.7"
  # - "3.3" # Django 1.9 is not compatible with Python 3.3
  - "3.4"
  - "3.5"

install:
  - pip install -r requirements/dev.txt
  - pip install -r requirements/base.txt

script:
  - "PYTHONPATH=blog_api_auth DJANGO_SETTINGS_MODULE=blog_api_auth.settings django-admin test blog"
